import "./globals.css";
import type { Metadata } from "next";
import Header from "./Header";
import Provider from "./Provider";
import {ThemeProvider} from "next-themes"
export const metadata: Metadata = {
  title: "NewsApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <Provider>
        <body className="bg-gray-100 dark:bg-zinc-900 transition-all duration-700">
          <Header />
          <div className="max-w-6xl mx-auto">{children}</div>
        </body>
      </Provider>
    </html>
  );
}
